description: Checks for PACI Parallels Cloud Server role
includes: [ lincommon, lin.oa.managed.fw, vz.fw ]
firewall:
- name: incoming
  networks: [backnet]
  ports: 64000,22
  connect_with: {roles: [oacivzbn, oacivz]}
- name: public_vnc
  type: internet
  ports: 5800-6800
  connect_with: {hosts: any}
requirements:
  OS: 'Virtuozzo Linux release 7\.'
  virtualization: 'bare metal'
  ram(GB): 2
  swap(GB): 4
  cpu-frequency: 1.5
  /: 12
  /vz: 88
  networks: [backnet, frontnet]
  storage_roles: { type: manual, value: 'Be sure to use vzstorage roles servers.yaml if VZ storage cluster is used' }
